import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture, spec, profile, Z1, Z2, T, A, PASSWORD } from './helpers.mjs';
import { buildRoutePlan, buildRollbackPlan, buildDeletePlan, syncProfileRoutes, applyAction, planDNS, discoverRoutes, checkEdge, observe, validationActions } from '../worker/planner.mjs';
import { Cloudflare } from '../worker/cloudflare.mjs';

test('Worker API flow: SSL pending does not block cutover and unrelated Tunnel config is retained', async () => {
  const f = await fixture(); await f.login(); const before = structuredClone(f.cf.config);
  const { plan, job } = await f.submit(); assert.equal(f.cf.writes().length, 0); assert(plan.actions.some(a => a.phase === 'cutover'));
  let current = await f.advance(job.id); assert.equal(current.status, 'waiting'); assert(!f.cf.rows(Z2).some(r => r.name === spec.publicHostname));
  assert.equal(f.cf.config.ingress.length, 4); assert.deepEqual(f.cf.config.ingress[0], before.ingress[0]); assert.deepEqual(f.cf.config.originRequest, before.originRequest); assert.deepEqual(f.cf.config['warp-routing'], before['warp-routing']);
  assert(f.cf.rows(Z2).some(r => r.name === `_cf-custom-hostname.${spec.publicHostname}` && r.type === 'TXT'));
  assert(f.cf.rows(Z2).some(r => r.name === `_acme-challenge.${spec.publicHostname}` && r.content.endsWith('.dcv.cloudflare.com')));
  f.cf.customs[0].status = 'active'; current = await f.advance(job.id); assert.equal(current.status, 'done');
  const dns = f.cf.rows(Z2).find(r => r.name === spec.publicHostname); assert.equal(dns.proxied, false); assert.equal(dns.content, spec.edgeHostname);
  const route = await f.ctx.get(`route:${plan.routeId}`); assert.equal(route.observed.sslStatus, 'pending_validation'); assert.equal(route.observed.status, 'ready'); assert.equal(route.maintenanceEnabled, true);
  assert(!JSON.stringify([...f.storage.data]).includes('NEVER-STORE-THIS-PRIVATE-KEY'));
});
test('immediate cutover is explicit and still reports pending certificate', async () => { const f = await fixture(); await f.login(); const { job } = await f.submit({ ...spec, cutover: 'immediate' }); const result = await f.advance(job.id); assert.equal(result.status, 'waiting'); assert(f.cf.rows(Z2).some(r => r.name === spec.publicHostname)); });
test('TXT auto fallback preserves existing proof and creates separate ownership record', async () => {
  const f = await fixture(); f.cf.rows(Z2).push({ id: 'other-proof', type: 'TXT', name: `_acme-challenge.${spec.publicHostname}`, content: 'foreign-proof', ttl: 60 }); await f.login(); const { job, plan } = await f.submit(); assert.equal(plan.dcvSuffix, null); await f.advance(job.id); const proofs = f.cf.rows(Z2).filter(r => r.name.startsWith('_acme')); assert.equal(proofs.length, 2); assert(proofs.some(r => r.content === 'foreign-proof'));
});
test('delegated-only conflicts with existing TXT without any cloud write', async () => { const f = await fixture(); await f.ctx.put('profile:profile-1', { ...profile, validationMode: 'delegated' }); f.cf.rows(Z2).push({ id: 'proof', type: 'TXT', name: `_acme-challenge.${spec.publicHostname}`, content: 'foreign-proof' }); await assert.rejects(buildRoutePlan(f.ctx, spec), { code: 'DNS_CONFLICT' }); assert.equal(f.cf.writes().length, 0); });
test('delegation falls back only for permission/not-found, never for network/rate failures', async () => {
  const f = await fixture(); f.cf.uuidStatus = 403; assert.equal((await buildRoutePlan(f.ctx, spec)).dcvSuffix, null); f.cf.uuidStatus = 429; await assert.rejects(buildRoutePlan(f.ctx, spec), { code: 'CF_RATE_LIMIT' });
});
test('all known conflicts caught before first write, including late public DNS conflict', async () => { const f = await fixture(); f.cf.rows(Z2).push({ id: 'existing-ip', type: 'A', name: spec.publicHostname, content: '192.0.2.9' }); await assert.rejects(buildRoutePlan(f.ctx, spec), { code: 'DNS_CONFLICT' }); assert.equal(f.cf.writes().length, 0); });
test('source/proxy DNS and external loops block safe plan', async () => { const f = await fixture(); f.cf.rows(Z1)[0].proxied = true; await assert.rejects(checkEdge(f.ctx, profile, profile.edgeHostname), { code: 'EDGE_PROXIED' }); f.cf.rows(Z1)[0].proxied = false; f.cf.rows(Z1)[0].content = profile.edgeHostname; await assert.rejects(checkEdge(f.ctx, profile, profile.edgeHostname), { code: 'DNS_LOOP' }); });
test('local-managed tunnel never mutated', async () => { const f = await fixture(); f.cf.tunnel.remote_config = false; await assert.rejects(buildRoutePlan(f.ctx, spec), { code: 'LOCAL_TUNNEL' }); assert.equal(f.cf.writes().length, 0); });
test('stale preview rejects unrelated tunnel changes instead of replaying snapshot', async () => { const f = await fixture(); await f.login(); const { body: plan } = await f.request('/plans', 'POST', spec); f.cf.config.ingress.splice(1, 0, { hostname: 'new.a.example', service: 'http://new:8000' }); const result = await f.request(`/plans/${plan.id}/apply`, 'POST', { acknowledge: true, confirmHostname: spec.publicHostname }); assert.equal(result.response.status, 409); assert.equal(result.body.error.code, 'STALE_PLAN'); assert.equal(f.cf.writes().length, 0); });
test('execution guards every action after approval, not only preview', async () => { const f = await fixture(); await f.login(); const { job } = await f.submit(); f.cf.config.originRequest.connectTimeout = 31; const result = await f.advance(job.id); assert.equal(result.status, 'failed'); assert.equal(result.error.code, 'STALE_PLAN'); assert.equal(f.cf.writes().length, 0); });
test('normal apply only needs one acknowledgement and remains idempotent', async () => { const f = await fixture(); await f.login(); const { body: plan } = await f.request('/plans', 'POST', spec); assert.equal((await f.request(`/plans/${plan.id}/apply`, 'POST', {})).response.status, 400); const a = await f.request(`/plans/${plan.id}/apply`, 'POST', { acknowledge: true }), b = await f.request(`/plans/${plan.id}/apply`, 'POST', { acknowledge: true }); assert.equal(a.body.id, b.body.id); assert.equal((await f.ctx.list('job:')).length, 1); });
test('duplicate previews cannot create two managed records for same host', async () => { const f = await fixture(); await f.login(); const a = await f.request('/plans', 'POST', spec), b = await f.request('/plans', 'POST', spec); const first = await f.request(`/plans/${a.body.id}/apply`, 'POST', { acknowledge: true, confirmHostname: spec.publicHostname }); await f.advance(first.body.id); const second = await f.request(`/plans/${b.body.id}/apply`, 'POST', { acknowledge: true, confirmHostname: spec.publicHostname }); assert.equal(second.response.status, 409); assert.equal((await f.ctx.list('route:')).length, 1); });
test('lost DNS POST response is reconciled by unique marker, not blindly repeated', async () => {
  const f = await fixture(); const a = await planDNS(f.ctx, { credentialId: 'cred-2', zoneId: Z2, name: 'new.b.example', content: 'edge.a.example', routeId: 'r1' }); let persisted;
  f.cf.interrupt = (p, m) => p.endsWith('dns_records') && m === 'POST'; await assert.rejects(applyAction(f.ctx, a, async () => { persisted = structuredClone(a); })); assert.equal(a.state, 'writing'); assert.equal(persisted.state, 'writing');
  await applyAction(f.ctx, persisted, async () => {}); assert.equal(persisted.state, 'done'); assert.equal(f.cf.writes().filter(c => c.method === 'POST').length, 1);
});
test('interrupted TXT creation reconciles quoted API canonical form', async () => { const f = await fixture(); f.cf.quoteTXT = true; const a = await planDNS(f.ctx, { credentialId: 'cred-2', zoneId: Z2, name: '_acme-challenge.new.b.example', content: 'proof', routeId: 'r1', type: 'TXT' }); f.cf.interrupt = (p, m) => m === 'POST'; await assert.rejects(applyAction(f.ctx, a, async () => {})); await applyAction(f.ctx, a, async () => {}); assert.equal(a.state, 'done'); assert.equal(f.cf.writes().length, 1); });
test('do not claim matching foreign DNS as own interrupted POST', async () => { const f = await fixture(); const a = await planDNS(f.ctx, { credentialId: 'cred-2', zoneId: Z2, name: 'new.b.example', content: 'edge.a.example', routeId: 'r1' }); a.state = 'writing'; f.cf.rows(Z2).push({ id: 'foreign', ...a.after, comment: 'not-cloudlane' }); await assert.rejects(applyAction(f.ctx, a, async () => {}), { code: 'STALE_PLAN' }); });
test('failed job with uncertain write cannot be rolled back before reconciliation', async () => { const f = await fixture(); await f.login(); const { job } = await f.submit(); const j = await f.ctx.get(`job:${job.id}`); j.status = 'paused'; j.actions[0].state = 'writing'; await f.ctx.put(`job:${job.id}`, j); await assert.rejects(buildRollbackPlan(f.ctx, j), { code: 'UNCERTAIN_WRITE' }); });
test('rollback restores exact original config and deletes only newly created route resources', async () => {
  const f = await fixture(); await f.login(); const original = structuredClone(f.cf.config); f.cf.nextCustomStatus = 'active'; f.cf.nextSSLStatus = 'active'; const { job, plan } = await f.submit(); const done = await f.advance(job.id); assert.equal(done.status, 'done');
  const inverse = await buildRollbackPlan(f.ctx, done); await f.ctx.put(`plan:${inverse.id}`, inverse); const applied = await f.request(`/plans/${inverse.id}/apply`, 'POST', { acknowledge: true, confirmHostname: spec.publicHostname }); assert.equal(applied.response.status, 202); const result = await f.advance(applied.body.id); assert.equal(result.status, 'done'); assert.deepEqual(f.cf.config, original); assert.equal(f.cf.customs.length, 0); assert.equal(f.cf.rows(Z2).length, 0); assert.equal(f.cf.rows(Z1).length, 1); assert.equal(f.cf.rows(Z1)[0].comment, 'owned by someone else'); assert.equal(await f.ctx.get(`route:${plan.routeId}`), undefined);
});
test('rollback refuses overwriting a newer unrelated tunnel change', async () => { const f = await fixture(); await f.login(); f.cf.nextCustomStatus = 'active'; f.cf.nextSSLStatus = 'active'; const { job } = await f.submit(); const done = await f.advance(job.id); f.cf.config.ingress.splice(0, 0, { hostname: 'new.a.example', service: 'http://localhost:3333' }); await assert.rejects(buildRollbackPlan(f.ctx, done), { code: 'ROLLBACK_DRIFT' }); });
test('dynamic validation returned outside the authorized hostname is never written', async () => { const f = await fixture(); await f.login(); const { job } = await f.submit(); const waiting = await f.advance(job.id); f.cf.customs[0].ownership_verification.name = '_cf-custom-hostname.victim.b.example'; const count = f.cf.writes().length; await assert.rejects(validationActions(f.ctx, waiting), { code: 'VALIDATION_SCOPE' }); assert.equal(f.cf.writes().length, count); });
test('discovery and import are read-only and preserve existing services and proof', async () => {
  const f = await fixture(); await f.login(); f.cf.nextCustomStatus = 'active'; f.cf.nextSSLStatus = 'active'; const { job, plan } = await f.submit(); await f.advance(job.id); await f.ctx.del(`route:${plan.routeId}`); const count = f.cf.writes().length; const candidates = await discoverRoutes(f.ctx, profile); assert.equal(candidates.length, 1); assert(candidates[0].importable);
  const imported = await f.request('/profiles/profile-1/import', 'POST', { hostnames: [spec.publicHostname] }); assert.equal(imported.body.imported[0].maintenanceEnabled, false); assert.equal(imported.body.imported[0].service, spec.service); assert.equal(f.cf.writes().length, count); assert.equal((await discoverRoutes(f.ctx, profile)).length, 0);
});
test('import refuses path-specific or mismatched pairs', async () => { const f = await fixture(); await f.login(); const { job } = await f.submit(); const j = await f.advance(job.id); await f.ctx.del(`route:${j.plan.routeId}`); f.cf.config.ingress.find(x => x.hostname === spec.publicHostname).service = 'http://different:123'; assert.equal((await discoverRoutes(f.ctx, profile))[0].importable, false); });
test('expired preview, maximum waiting period and detach/retry are guarded', async () => {
  const f = await fixture(); await f.login(); const p = await buildRoutePlan(f.ctx, spec); p.expiresAt = Date.now() - 1; await f.ctx.put(`plan:${p.id}`, p); assert.equal((await f.request(`/plans/${p.id}/apply`, 'POST', { acknowledge: true, confirmHostname: spec.publicHostname })).body.error.code, 'PLAN_EXPIRED');
  const { job, plan } = await f.submit(); const j = await f.ctx.get(`job:${job.id}`); j.deadline = Date.now() - 1; await f.ctx.advance(j); assert.equal((await f.ctx.get(`job:${job.id}`)).status, 'paused'); const count = f.cf.writes().length;
  assert.equal((await f.request(`/routes/${plan.routeId}`, 'DELETE', { acknowledge: true, confirmHostname: spec.publicHostname })).response.status, 200); assert.equal((await f.request(`/jobs/${job.id}/retry`, 'POST', {})).body.error.code, 'ROUTE_DETACHED'); assert.equal(f.cf.writes().length, count);
});
test('missing fallback requires explicit opt-in; shared infrastructure retained on rollback', async () => { const f = await fixture(); f.cf.fallback = null; await assert.rejects(buildRoutePlan(f.ctx, spec), { code: 'FALLBACK_MISSING' }); await f.ctx.put('profile:profile-1', { ...profile, initializeFallback: true }); const plan = await buildRoutePlan(f.ctx, spec); assert(plan.actions.some(a => a.kind === 'fallback')); assert(plan.actions.filter(a => a.role === 'shared_fallback').length === 2); });
test('same origin is not managed twice through different profiles', async () => { const f = await fixture(); await f.ctx.put('route:existing', { ...spec, id: 'existing', profileId: 'another', publicHostname: 'other.b.example' }); await assert.rejects(buildRoutePlan(f.ctx, spec), { code: 'DUPLICATE_ROUTE' }); });
test('auth, CSRF, password rotation, token redaction, and login limits', async () => {
  const f = await fixture(); assert.equal((await f.request('/state')).response.status, 401); const result = await f.login(); assert.equal(result.response.status, 200); assert.match(result.response.headers.get('set-cookie'), /HttpOnly; SameSite=Strict.*Secure/);
  const state = await f.request('/state'); assert(!JSON.stringify(state.body).includes('source-token')); assert(!state.body.credentials[0].secret);
  assert.equal((await f.request('/plans', 'POST', spec, { Origin: 'https://attacker.example' })).response.status, 403);
  assert.equal((await f.request('/plans', 'POST', '{')).response.status, 400); assert.equal((await f.request('/plans', 'POST', 'x'.repeat(66000))).response.status, 413);
  f.env.ADMIN_PASSWORD = 'different-long-enough-password'; assert.equal((await f.request('/state')).response.status, 401);
  const g = await fixture(); for (let i = 0; i < 8; i++) await g.request('/login', 'POST', { password: 'wrong' }); assert.equal((await g.login()).response.status, 429);
});
test('credential API probes zones, encrypts token, and catalogs cross-account public zone separately', async () => { const f = await fixture(); await f.login(); const result = await f.request('/credentials', 'POST', { accountId: A, label: 'new source', token: 'test-unpersisted-plaintext' }); assert.equal(result.response.status, 201); assert(!JSON.stringify(result.body).includes('token')); const row = await f.ctx.get(`credential:${result.body.id}`); assert(row.secret.data); assert(!JSON.stringify(row).includes('test-unpersisted-plaintext')); const catalog = await f.request('/credentials/cred-2/catalog'); assert.equal(catalog.body.zones[0].id, Z2); });
test('CF client permits paginated /zones query and sanitizes error token', async () => { let pages = 0; const cf = new Cloudflare('secret123', async url => { pages++; return Response.json({ success: true, result: Array(50).fill({ id: pages }), result_info: { total_pages: 2 } }); }); assert.equal((await cf.list('/zones')).length, 100); assert.equal(pages, 2); const err = new Cloudflare('secret123', async () => Response.json({ success: false, errors: [{ message: 'secret123 bad credential' }] }, { status: 403 })); await assert.rejects(err.get('/zones'), e => e.status === 403 && !e.message.includes('secret123')); });
test('CF client reports runtime fetch failures without falsely calling them timeouts or leaking the token', async () => {
  const cf = new Cloudflare('secret123', async () => { throw new TypeError('Workers routing failed for secret123'); });
  await assert.rejects(cf.get('/zones'), error => error.code === 'CF_NETWORK'
    && error.message.includes('Workers routing failed')
    && !error.message.includes('超时')
    && !error.message.includes('secret123'));
});
test('pagination limit stops instead of falsely calling a partial listing complete', async () => { const cf = new Cloudflare('token', async () => Response.json({ success: true, result: Array(50).fill({ id: 'x' }), result_info: { total_pages: 3 } })); await assert.rejects(cf.list('/zones', {}, 2), { code: 'SCAN_LIMIT' }); });